services:
  - type: web
    name: cybix-v1
    env: node
    plan: free
    buildCommand: "yarn install"
    startCommand: "yarn start"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 3000
