services:
  - type: web
    name: cybix-v1
    env: node
    plan: free
    buildCommand: "yarn install --no-progress --frozen-lockfile || yarn install"
    startCommand: "yarn start"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
    healthCheckPath: /
    autoDeploy: true
    preDeployCommand: |
      if [ -z "$BOT_TOKEN" ]; then
        echo "❌ BOT_TOKEN is not set. Configure it in Render Environment Variables."
        exit 1
      fi
